#pragma config(Motor,  port2,           FrontPass,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           FrontDriv,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           RearDriv,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           RearPass,      tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while (1){
 motor[RearDriv] = vexRT[Ch3];
 motor[RearPass] = vexRT[Ch3];
 motor[FrontPass] = vexRT[Ch1];
 motor[FrontDriv] = vexRT[Ch1];

  }
}
